---
kind: pipeline
name: default

steps:
- name: fails
  image: alpine:latest
  commands:
    - apk update && apk add make
    - make
  failure: ignore


- name: succeeds
  image: alpine:3.13
  commands:
    - apk update && apk add make
    - make
